# .bashrc

# User specific aliases and functions

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi
export PATH=/home/spol/projDir/rvp8/scripts:/home/spol/projDir/bin:/home/spol/projDir/system/scripts:/usr/sigmet/bin:/usr/sigmet/bin/rda:$PATH
# keep cursor in sync for Avocent KVM
xset m 1 1

alias matlab='/usr/local/MATLAB/R2011a/bin/matlab'

