#! /bin/csh -f

#get sun cal data
# script needs to be called with start and end date
#"2019 01 01 00 00 00" "2019 01 31 23 59 59"

set PLOT_DIR="$DATA_DIR/eolbase/catalog/images/spol_sunCal/2021/"

set START_TIME="$1"
set END_TIME="$2"

set START_NOSPACE=`echo $START_TIME | sed 's/ //g'`
set START1=`echo $START_NOSPACE | awk '{print substr($0,0,8)}'`
set START2=`echo $START_NOSPACE | awk '{print substr($0,9,6)}'`

set END_NOSPACE=`echo $END_TIME | sed 's/ //g'`
set END1=`echo $END_NOSPACE | awk '{print substr($0,0,8)}'`
set END2=`echo $END_NOSPACE | awk '{print substr($0,9,6)}'`

SpdbXml2Table -params ~/git/lrose-projects-eolbase/projDir/cal/params/SpdbXml2Table.suncal -start "$START_TIME" -end "$END_TIME" > "$DATA_DIR/eolbase/tables/spolSunCal/spolSunCal_"$START1"_"$START2"_to_"$END1"_"$END2".txt"

~/git/lrose-projects-eolbase/projDir/monitoring/scripts/monitorSunCal.py --start "$START_TIME" --end "$END_TIME" --figDir $PLOT_DIR --suncalFile "$DATA_DIR/eolbase/tables/spolSunCal/spolSunCal_"$START1"_"$START2"_to_"$END1"_"$END2".txt"
