#! /bin/csh -f

# This script is for automatic monitoring of spol. It is supposed to run
# every xx minutes. It creates plots with spol data for yy hours. It
# takes the data between the start time of the latest plot in an
# output directory (PLOT_DIR) and the current time and plots it in the
# latest plot until yy hours have been filled. Then it starts a new plot.

set PLOT_DIR="$DATA_DIR/eolbase/catalog/images/spol_mon/2021/"

# Get start time for last file in PLOT_DIR and set it as START_TIME
set LAST_FILE_FULL="`ls $PLOT_DIR"radar.SPOL.*.Monitoring.png" | tail -1`"
set LAST_FILE="`basename $LAST_FILE_FULL`"
set START_NOMINS=`echo $LAST_FILE | awk '{print substr($0,12,12)}'`
set START_NOSPACE=`echo $START_NOMINS"00"`
set SY=`echo $START_NOSPACE | awk '{print substr($0,0,4)}'`
set SM=`echo $START_NOSPACE | awk '{print substr($0,5,2)}'`
set SD=`echo $START_NOSPACE | awk '{print substr($0,7,2)}'`
set SHH=`echo $START_NOSPACE | awk '{print substr($0,9,2)}'`
set SMM=`echo $START_NOSPACE | awk '{print substr($0,11,2)}'`
set SSS=`echo $START_NOSPACE | awk '{print substr($0,13,2)}'`

set START_TIME=`echo $SY" "$SM" "$SD" "$SHH" "$SMM" "$SSS`

set START_NOSPACE=`echo $START_TIME | sed 's/ //g'`
set START1=`echo $START_NOSPACE | awk '{print substr($0,0,8)}'`
set START2=`echo $START_NOSPACE | awk '{print substr($0,9,6)}'`

# Get current time and set it as END_TIME
set END_NOSPACE="`date -u +"%Y%m%d%H%M%S"`"
set EY=`echo $END_NOSPACE | awk '{print substr($0,0,4)}'`
set EM=`echo $END_NOSPACE | awk '{print substr($0,5,2)}'`
set ED=`echo $END_NOSPACE | awk '{print substr($0,7,2)}'`
set EHH=`echo $END_NOSPACE | awk '{print substr($0,9,2)}'`
set EMM=`echo $END_NOSPACE | awk '{print substr($0,11,2)}'`
set ESS=`echo $END_NOSPACE | awk '{print substr($0,13,2)}'`

set END_TIME=`echo $EY" "$EM" "$ED" "$EHH" "$EMM" "$ESS`

set END_NOSPACE=`echo $END_TIME | sed 's/ //g'`
set END1=`echo $END_NOSPACE | awk '{print substr($0,0,8)}'`
set END2=`echo $END_NOSPACE | awk '{print substr($0,9,6)}'`

# Make table from SPDB files
SpdbXml2Table -params ~/git/lrose-projects-eolbase/projDir/qc/params/SpdbXml2Table.monitor.sband -start "$START_TIME" -end "$END_TIME" > $DATA_DIR/eolbase/tables/spolMon/spolMon_"$START1"_"$START2"_to_"$END1"_"$END2".txt

# Run python code to create plots
~/git/lrose-projects-eolbase/projDir/monitoring/scripts/monitorSpol.py --start "$START_TIME" --end "$END_TIME" --figDir $PLOT_DIR --monFile $DATA_DIR/eolbase/tables/spolMon/spolMon_"$START1"_"$START2"_to_"$END1"_"$END2".txt --plotHours 6 --printTable 0

