#! /bin/csh
#

check_dial_rsync.py --debug \
    --dataDir /scr/eldora1/wvdial_1_data \
    --maxDelayMins 15 \
    --emails "stillwel@ucar.edu, brads@ucar.edu" |& \
    LogFilter -d $ERRORS_LOG_DIR -p check_dial_rsync.py -i wvdial_01 >& /dev/null &

check_dial_rsync.py --debug \
    --dataDir /scr/eldora1/wvdial_2_data \
    --maxDelayMins 15 \
    --emails "stillwel@ucar.edu, brads@ucar.edu" |& \
    LogFilter -d $ERRORS_LOG_DIR -p check_dial_rsync.py -i wvdial_02 >& /dev/null &

check_dial_rsync.py --debug \
    --dataDir /scr/eldora1/wvdial_3_data \
    --maxDelayMins 15 \
    --emails "stillwel@ucar.edu, brads@ucar.edu" |& \
    LogFilter -d $ERRORS_LOG_DIR -p check_dial_rsync.py -i wvdial_03 >& /dev/null &

